### ISSUE TITLE
Fixing the Break from Item 5 "Modernize Dependencies and Packaging"

### ISSUE THREAD

**Issue by dazzaji** [PrototypeJam/lake_merritt#34]
### The Definitive Fix (Version 7)

Here is a single, authoritative memo that replaces all previous versions. It follows Claude's recommended path of sticking with `pip` and `setuptools`. Following these steps in order will resolve all your errors.

# Technical Memo: Action Plan for Lake Merritt v0.6 (Version 7 - Final)

**DATE:** June 16, 2024  
**SUBJECT:** Definitive Fix for CI and Streamlit Cloud Dependency Failures

## 1. Executive Summary

This document provides a single, unified action plan to resolve the dependency conflicts currently blocking CI tests and Streamlit Cloud deployments. The root cause is an incomplete migration to using `pyproject.toml` and a Python version incompatibility with Streamlit Cloud. This plan will stabilize the project using the standard `pip` and `setuptools` toolchain without introducing new tools like Poetry.

## 2. Action Plan (Implement in Order)

This is a single, cohesive fix. All steps should be performed as part of one commit.

### Step 1: Correct the `pyproject.toml` File

**Problem:** The current `pyproject.toml` allows the use of Python 3.9.7, which is explicitly blocked by Streamlit, causing the deployment failure.

**Action:** Replace the entire content of your `pyproject.toml` file with the following corrected version. The key change is `requires-python = ">=3.9, !=3.9.7"`.

```toml
# In file: pyproject.toml

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-eval-workbench"
version = "0.1.0"
description = "Lake Merritt is a modular platform for evaluating AI models and applications"
readme = "README.md"
requires-python = ">=3.9, !=3.9.7"
license = {text = "MIT"}

dependencies = [
    "streamlit>=1.28.0",
    "pandas>=2.0.0",
    "pydantic>=2.0.0",
    "openai>=1.0.0",
    "anthropic>=0.18.0",
    "google-generativeai>=0.3.0",
    "python-dotenv>=1.0.0",
    "rapidfuzz>=3.6.0",
    "aiofiles>=23.0.0",
    "numpy>=1.24.0",
    "nest-asyncio>=1.5",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.0.0",
]
dev = [
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0",
]
```

### Step 2: Correct the CI Workflow File

**Problem:** The current `.github/workflows/ci.yml` is trying to install from a deleted `requirements.txt` file, causing the CI jobs to fail.

**Action:** Replace the entire content of your `.github/workflows/ci.yml` file with this corrected version. The key change is replacing `pip install -r requirements.txt` with `pip install -e ".[test,dev]"`.

```yaml
# In file: .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run Linters
      run: |
        black --check .
        isort --check-only .
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        mypy . --ignore-missing-imports

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"

    - name: Run Tests
      run: pytest -v -m "not requires_api" --cov=core --cov-report=term-missing
```
*(Note: I have simplified the CI file slightly by combining linter commands and removing redundant test commands for clarity and efficiency.)*

### Step 3: Create `runtime.txt` for Streamlit Cloud

**Problem:** We need to explicitly tell Streamlit Cloud which safe version of Python to use for deployment to avoid its default, which may be the problematic 3.9.7.

**Action:** Create a new file in the **root directory** of your project named `runtime.txt`. The file should contain only this single line:

```
python-3.11
```

### Step 4: Commit Your Changes

**Problem:** All these changes need to be saved to your repository.

**Action:** Stage and commit all the changed and new files.

```bash
git add pyproject.toml .github/workflows/ci.yml runtime.txt
git commit -m "fix(deps): Unify on setuptools and fix CI/deployment failures"
git push
```

## 3. Your New Local Workflow

Your local development workflow is now simpler and more robust. To set up your environment from scratch, the commands are:

```bash
# 1. Create virtual environment (no change)
uv venv venv

# 2. Activate environment (no change)
source venv/bin/activate

# 3. Install project in editable mode with test/dev tools (THE NEW COMMAND)
uv pip install -e ".[test,dev]"

# 4. Run the app (no change)
streamlit run streamlit_app.py
```

## 4. Expected Outcome

1.  Your GitHub Actions CI will now pass successfully.
2.  Your Streamlit Cloud deployment will build and run without errors.
3.  Your local development setup will be consistent and reliable.

________________

# CONTEXT

The problems relate to implementing the following "fix"

### Item 5: Modernize Dependencies and Packaging

**File(s) to Modify:** `pyproject.toml`, `requirements.txt`, `core/scoring/fuzzy_match.py`, `core/scoring/__init__.py`, `README.md`, `AGENTS.md`

**Problem Statement:** The project uses `requirements.txt` and the slow, unmaintained `fuzzywuzzy` library. Modern Python projects use `pyproject.toml` and separate runtime from development dependencies.

**Implementation Plan:**

1.  **Replace `fuzzywuzzy` with `rapidfuzz`:**
    *   In `requirements.txt`, replace the `fuzzywuzzy` and `python-Levenshtein` lines with `rapidfuzz>=3.6.0`.
    *   In `core/scoring/fuzzy_match.py`, change the import to `from rapidfuzz import fuzz`.
    *   Delete the entire `LevenshteinScorer` class from `fuzzy_match.py` and remove its registration from `core/scoring/__init__.py`.

2.  **Consolidate dependencies into `pyproject.toml` with proper separation:**
    *   In `pyproject.toml`, remove the `dynamic = ["dependencies"]` line.
    *   In the `[tool.setuptools.dynamic]` section, remove the `dependencies` entry entirely.
    *   Add the following `dependencies` and `optional-dependencies` keys to the `[project]` section:
        ```toml
        [project]
        # ... (rest of the project metadata) ...
        dependencies = [
            "streamlit>=1.28.0",
            "pandas>=2.0.0",
            "pydantic>=2.0.0",
            "openai>=1.0.0",
            "anthropic>=0.18.0",
            "google-generativeai>=0.3.0",
            "python-dotenv>=1.0.0",
            "rapidfuzz>=3.6.0",
            "aiofiles>=23.0.0",
            "numpy>=1.24.0",
            "nest-asyncio>=1.5",
        ]
     
        [project.optional-dependencies]
        test = [
            "pytest>=7.0.0",
            "pytest-asyncio>=0.21.0",
            "pytest-cov>=4.0.0",
        ]
        dev = [
            "black>=23.0.0",
            "isort>=5.12.0",
            "flake8>=6.0.0",
            "mypy>=1.0.0",
        ]
        ```

3.  **Delete `requirements.txt`** - it's now redundant.

4.  **Update installation instructions** in `README.md` and `AGENTS.md` to use the new standard. Replace old `pip install -r requirements.txt` commands with:
    ```bash
    # For development (includes testing and linting tools):
    pip install -e ".[test,dev]"

    # For standard installation:
    pip install .
    ```
